server:
  port: 8001
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3339/geektime-eshop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    hikari:
      connectionTimeout: 1000
      validationTimeout: 1000
      idleTimeout: 30000
      maxLifetime: 60000
      maximumPoolSize: 3
      minimumIdle: 1