server:
  port: 8001
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3339/db?useUnicode=true&autoReconnect=true&failOverReadOnly=false&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
          username: root
          password: 123456
        slave_1:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3340/db?useUnicode=true&autoReconnect=true&failOverReadOnly=false&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
          username: root
          password: 123456