server:
  port: 8088
  address: 0.0.0.0
  servlet:
    context-path: /
mybatis:
  type-aliases-package: com.geektime.hmilydemo.common
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  application:
    name: dubbo-demo-provider
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmily?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
dubbo:
  scan:
    base-packages: io.kimmking.dubbo.demo.provider
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
